import type { SupportedLocale } from './catalog';
import { getRuntimeLocale } from './reactLocale';

export interface OverlayStrings {
  close: string;
  open: string;
  bookmarks: string;
  readingHistory: string;
  savedEntries: string;
  recentlyOpened: string;
  noBookmarks: string;
  noHistory: string;
  completeIndex: string;
  everyFiledTerm: string;
  entries: string;
  indexSections: string;
  updatedFieldEdition: string;
  filterIndex: string;
  filterTerms: string;
  filterCategory: string;
  allCategories: string;
  jumpToLetter: string;
  noEntriesUnder: string;
  noTermsMatch: string;
  clearFilter: string;
  timelineEyebrow: string;
  timelineTitle: string;
  openThisTerm: string;
  compareEyebrow: string;
  compareTitle: string;
  compareIntro: string;
  definition: string;
  inPractice: string;
  addThisEntry: string;
  addToCollection: string;
  collectionPickerClose: string;
  newCollectionName: string;
  create: string;
  collectionEntries: string;
  readingLists: string;
  collections: string;
  newCollection: string;
  collectionName: string;
  save: string;
  cancel: string;
  collection: string;
  deleteCollectionQuestion: string;
  delete: string;
  rename: string;
  noCollections: string;
  emptyCollection: string;
  entryUnavailable: string;
  remove: string;
  saveOrShare: string;
  saveThisEntry: string;
  saveIntro: string;
  savedEntry: string;
  definitionLower: string;
  inUse: string;
  pickPersonality: string;
  downloadPng: string;
  copyText: string;
  copyLink: string;
  share: string;
  tutorialLabel: string;
  tutorialHowTo: string;
  step: string;
  of: string;
  closeTutorial: string;
  back: string;
  finish: string;
  next: string;
  skipTutorial: string;
}

const en: OverlayStrings = {
  close: 'Close', open: 'open', bookmarks: 'Bookmarks', readingHistory: 'Reading history', savedEntries: 'saved entries', recentlyOpened: 'recently opened', noBookmarks: 'No bookmarks yet.', noHistory: 'No reading history yet.', completeIndex: 'complete index', everyFiledTerm: 'Every filed term', entries: 'entries', indexSections: 'index sections', updatedFieldEdition: 'updated field edition', filterIndex: 'Filter the complete index', filterTerms: 'Filter terms, aliases, or categories…', filterCategory: 'Filter by category', allCategories: 'All categories', jumpToLetter: 'Jump to index letter', noEntriesUnder: 'No entries under', noTermsMatch: 'No terms match', clearFilter: 'Clear filter', timelineEyebrow: 'timeline', timelineTitle: 'How the terms developed', openThisTerm: 'Open this term', compareEyebrow: 'side-by-side reading', compareTitle: 'Compare terms', compareIntro: 'Read both definitions in the same frame, then open either entry for its full field note.', definition: 'Definition', inPractice: 'In practice', addThisEntry: 'Add this entry', addToCollection: 'Add to collection', collectionPickerClose: 'Close collection picker', newCollectionName: 'New collection name', create: 'Create', collectionEntries: 'entries', readingLists: 'reading lists', collections: 'Collections', newCollection: 'New collection', collectionName: 'Collection name', save: 'Save', cancel: 'Cancel', collection: 'Collection', deleteCollectionQuestion: 'Delete this collection?', delete: 'Delete', rename: 'Rename', noCollections: 'No collections yet. Create one from the field on the left.', emptyCollection: 'This collection has no entries yet.', entryUnavailable: 'Entry unavailable', remove: 'remove', saveOrShare: 'save or share', saveThisEntry: 'Save this entry', saveIntro: 'Choose a visual voice for the entry. The words stay the same; the treatment changes.', savedEntry: 'SAVED ENTRY', definitionLower: 'definition', inUse: 'in use', pickPersonality: 'Pick a personality', downloadPng: 'Download PNG', copyText: 'Copy text', copyLink: 'Copy link', share: 'Share', tutorialLabel: 'The AI Almanac tutorial', tutorialHowTo: 'How to use The AI Almanac', step: 'Step', of: 'of', closeTutorial: 'Close tutorial', back: 'Back', finish: 'Finish', next: 'Next', skipTutorial: 'Skip tutorial'
};

const overlays: Record<Exclude<SupportedLocale, 'en'>, OverlayStrings> = {
  es: { ...en, close:'Cerrar', open:'abrir', bookmarks:'Marcadores', readingHistory:'Historial de lectura', savedEntries:'entradas guardadas', recentlyOpened:'abiertas recientemente', noBookmarks:'Aún no hay marcadores.', noHistory:'Aún no hay historial de lectura.', completeIndex:'índice completo', everyFiledTerm:'Todos los términos archivados', entries:'entradas', indexSections:'secciones del índice', updatedFieldEdition:'edición de campo actualizada', filterIndex:'Filtrar el índice completo', filterTerms:'Filtrar términos, alias o categorías…', filterCategory:'Filtrar por categoría', allCategories:'Todas las categorías', jumpToLetter:'Ir a una letra del índice', noEntriesUnder:'No hay entradas en', noTermsMatch:'Ningún término coincide con', clearFilter:'Limpiar filtro', timelineEyebrow:'cronología', timelineTitle:'Cómo evolucionaron los términos', openThisTerm:'Abrir este término', compareEyebrow:'lectura en paralelo', compareTitle:'Comparar términos', compareIntro:'Lee ambas definiciones juntas y abre cualquiera de las entradas para ver su nota completa.', definition:'Definición', inPractice:'En la práctica', addThisEntry:'Añadir esta entrada', addToCollection:'Añadir a colección', collectionPickerClose:'Cerrar selector de colección', newCollectionName:'Nombre de la nueva colección', create:'Crear', collectionEntries:'entradas', readingLists:'listas de lectura', collections:'Colecciones', newCollection:'Nueva colección', collectionName:'Nombre de la colección', save:'Guardar', cancel:'Cancelar', collection:'Colección', deleteCollectionQuestion:'¿Eliminar esta colección?', delete:'Eliminar', rename:'Renombrar', noCollections:'Aún no hay colecciones. Crea una desde el campo de la izquierda.', emptyCollection:'Esta colección todavía no tiene entradas.', entryUnavailable:'Entrada no disponible', remove:'quitar', saveOrShare:'guardar o compartir', saveThisEntry:'Guardar esta entrada', saveIntro:'Elige un estilo visual para la entrada. Las palabras se mantienen; cambia el tratamiento.', savedEntry:'ENTRADA GUARDADA', definitionLower:'definición', inUse:'en uso', pickPersonality:'Elige un estilo', downloadPng:'Descargar PNG', copyText:'Copiar texto', copyLink:'Copiar enlace', share:'Compartir', tutorialLabel:'Tutorial de The AI Almanac', tutorialHowTo:'Cómo usar The AI Almanac', step:'Paso', of:'de', closeTutorial:'Cerrar tutorial', back:'Atrás', finish:'Finalizar', next:'Siguiente', skipTutorial:'Omitir tutorial' },
  pt: { ...en, close:'Fechar', open:'abrir', bookmarks:'Favoritos', readingHistory:'Histórico de leitura', savedEntries:'entradas salvas', recentlyOpened:'abertas recentemente', noBookmarks:'Ainda não há favoritos.', noHistory:'Ainda não há histórico de leitura.', completeIndex:'índice completo', everyFiledTerm:'Todos os termos catalogados', entries:'entradas', indexSections:'seções do índice', updatedFieldEdition:'edição de campo atualizada', filterIndex:'Filtrar o índice completo', filterTerms:'Filtrar termos, aliases ou categorias…', filterCategory:'Filtrar por categoria', allCategories:'Todas as categorias', jumpToLetter:'Ir para uma letra do índice', noEntriesUnder:'Nenhuma entrada em', noTermsMatch:'Nenhum termo corresponde a', clearFilter:'Limpar filtro', timelineEyebrow:'linha do tempo', timelineTitle:'Como os termos se desenvolveram', openThisTerm:'Abrir este termo', compareEyebrow:'leitura lado a lado', compareTitle:'Comparar termos', compareIntro:'Leia as duas definições juntas e abra qualquer entrada para ver a nota completa.', definition:'Definição', inPractice:'Na prática', addThisEntry:'Adicionar esta entrada', addToCollection:'Adicionar à coleção', collectionPickerClose:'Fechar seletor de coleção', newCollectionName:'Nome da nova coleção', create:'Criar', collectionEntries:'entradas', readingLists:'listas de leitura', collections:'Coleções', newCollection:'Nova coleção', collectionName:'Nome da coleção', save:'Salvar', cancel:'Cancelar', collection:'Coleção', deleteCollectionQuestion:'Excluir esta coleção?', delete:'Excluir', rename:'Renomear', noCollections:'Ainda não há coleções. Crie uma no campo à esquerda.', emptyCollection:'Esta coleção ainda não tem entradas.', entryUnavailable:'Entrada indisponível', remove:'remover', saveOrShare:'salvar ou compartilhar', saveThisEntry:'Salvar esta entrada', saveIntro:'Escolha uma linguagem visual para a entrada. As palavras permanecem; o tratamento muda.', savedEntry:'ENTRADA SALVA', definitionLower:'definição', inUse:'em uso', pickPersonality:'Escolha um estilo', downloadPng:'Baixar PNG', copyText:'Copiar texto', copyLink:'Copiar link', share:'Compartilhar', tutorialLabel:'Tutorial do The AI Almanac', tutorialHowTo:'Como usar The AI Almanac', step:'Etapa', of:'de', closeTutorial:'Fechar tutorial', back:'Voltar', finish:'Concluir', next:'Próximo', skipTutorial:'Pular tutorial' },
  it: { ...en, close:'Chiudi', open:'apri', bookmarks:'Segnalibri', readingHistory:'Cronologia di lettura', savedEntries:'voci salvate', recentlyOpened:'aperte di recente', noBookmarks:'Nessun segnalibro.', noHistory:'Nessuna cronologia di lettura.', completeIndex:'indice completo', everyFiledTerm:'Tutti i termini archiviati', entries:'voci', indexSections:'sezioni dell’indice', updatedFieldEdition:'edizione da campo aggiornata', filterIndex:'Filtra l’indice completo', filterTerms:'Filtra termini, alias o categorie…', filterCategory:'Filtra per categoria', allCategories:'Tutte le categorie', jumpToLetter:'Vai a una lettera dell’indice', noEntriesUnder:'Nessuna voce sotto', noTermsMatch:'Nessun termine corrisponde a', clearFilter:'Cancella filtro', timelineEyebrow:'cronologia', timelineTitle:'Come si sono evoluti i termini', openThisTerm:'Apri questo termine', compareEyebrow:'lettura affiancata', compareTitle:'Confronta termini', compareIntro:'Leggi entrambe le definizioni insieme e apri una voce per la nota completa.', definition:'Definizione', inPractice:'In pratica', addThisEntry:'Aggiungi questa voce', addToCollection:'Aggiungi alla raccolta', collectionPickerClose:'Chiudi selettore raccolta', newCollectionName:'Nome della nuova raccolta', create:'Crea', collectionEntries:'voci', readingLists:'liste di lettura', collections:'Raccolte', newCollection:'Nuova raccolta', collectionName:'Nome raccolta', save:'Salva', cancel:'Annulla', collection:'Raccolta', deleteCollectionQuestion:'Eliminare questa raccolta?', delete:'Elimina', rename:'Rinomina', noCollections:'Nessuna raccolta. Creane una dal campo a sinistra.', emptyCollection:'Questa raccolta non contiene ancora voci.', entryUnavailable:'Voce non disponibile', remove:'rimuovi', saveOrShare:'salva o condividi', saveThisEntry:'Salva questa voce', saveIntro:'Scegli uno stile visivo per la voce. Le parole restano uguali; cambia il trattamento.', savedEntry:'VOCE SALVATA', definitionLower:'definizione', inUse:'in uso', pickPersonality:'Scegli uno stile', downloadPng:'Scarica PNG', copyText:'Copia testo', copyLink:'Copia link', share:'Condividi', tutorialLabel:'Tutorial di The AI Almanac', tutorialHowTo:'Come usare The AI Almanac', step:'Passaggio', of:'di', closeTutorial:'Chiudi tutorial', back:'Indietro', finish:'Fine', next:'Avanti', skipTutorial:'Salta tutorial' },
  fr: { ...en, close:'Fermer', open:'ouvrir', bookmarks:'Favoris', readingHistory:'Historique de lecture', savedEntries:'entrées enregistrées', recentlyOpened:'ouvertes récemment', noBookmarks:'Aucun favori pour le moment.', noHistory:'Aucun historique de lecture.', completeIndex:'index complet', everyFiledTerm:'Tous les termes classés', entries:'entrées', indexSections:'sections d’index', updatedFieldEdition:'édition de terrain mise à jour', filterIndex:'Filtrer l’index complet', filterTerms:'Filtrer les termes, alias ou catégories…', filterCategory:'Filtrer par catégorie', allCategories:'Toutes les catégories', jumpToLetter:'Aller à une lettre de l’index', noEntriesUnder:'Aucune entrée sous', noTermsMatch:'Aucun terme ne correspond à', clearFilter:'Effacer le filtre', timelineEyebrow:'chronologie', timelineTitle:'Comment les termes ont évolué', openThisTerm:'Ouvrir ce terme', compareEyebrow:'lecture côte à côte', compareTitle:'Comparer les termes', compareIntro:'Lisez les deux définitions ensemble puis ouvrez une entrée pour voir sa note complète.', definition:'Définition', inPractice:'En pratique', addThisEntry:'Ajouter cette entrée', addToCollection:'Ajouter à une collection', collectionPickerClose:'Fermer le sélecteur de collection', newCollectionName:'Nom de la nouvelle collection', create:'Créer', collectionEntries:'entrées', readingLists:'listes de lecture', collections:'Collections', newCollection:'Nouvelle collection', collectionName:'Nom de la collection', save:'Enregistrer', cancel:'Annuler', collection:'Collection', deleteCollectionQuestion:'Supprimer cette collection ?', delete:'Supprimer', rename:'Renommer', noCollections:'Aucune collection. Créez-en une avec le champ de gauche.', emptyCollection:'Cette collection ne contient encore aucune entrée.', entryUnavailable:'Entrée indisponible', remove:'retirer', saveOrShare:'enregistrer ou partager', saveThisEntry:'Enregistrer cette entrée', saveIntro:'Choisissez un style visuel pour l’entrée. Les mots restent identiques, seul le traitement change.', savedEntry:'ENTRÉE ENREGISTRÉE', definitionLower:'définition', inUse:'en usage', pickPersonality:'Choisir un style', downloadPng:'Télécharger le PNG', copyText:'Copier le texte', copyLink:'Copier le lien', share:'Partager', tutorialLabel:'Tutoriel The AI Almanac', tutorialHowTo:'Comment utiliser The AI Almanac', step:'Étape', of:'sur', closeTutorial:'Fermer le tutoriel', back:'Retour', finish:'Terminer', next:'Suivant', skipTutorial:'Ignorer le tutoriel' },
  de: { ...en, close:'Schließen', open:'öffnen', bookmarks:'Lesezeichen', readingHistory:'Leseverlauf', savedEntries:'gespeicherte Einträge', recentlyOpened:'kürzlich geöffnet', noBookmarks:'Noch keine Lesezeichen.', noHistory:'Noch kein Leseverlauf.', completeIndex:'vollständiger Index', everyFiledTerm:'Alle erfassten Begriffe', entries:'Einträge', indexSections:'Indexabschnitte', updatedFieldEdition:'aktualisierte Feldausgabe', filterIndex:'Vollständigen Index filtern', filterTerms:'Begriffe, Aliase oder Kategorien filtern…', filterCategory:'Nach Kategorie filtern', allCategories:'Alle Kategorien', jumpToLetter:'Zu einem Indexbuchstaben springen', noEntriesUnder:'Keine Einträge unter', noTermsMatch:'Keine Begriffe passen zu', clearFilter:'Filter löschen', timelineEyebrow:'Zeitleiste', timelineTitle:'Wie sich die Begriffe entwickelten', openThisTerm:'Diesen Begriff öffnen', compareEyebrow:'Direktvergleich', compareTitle:'Begriffe vergleichen', compareIntro:'Lies beide Definitionen nebeneinander und öffne einen Eintrag für die vollständige Notiz.', definition:'Definition', inPractice:'In der Praxis', addThisEntry:'Diesen Eintrag hinzufügen', addToCollection:'Zur Sammlung hinzufügen', collectionPickerClose:'Sammlungsauswahl schließen', newCollectionName:'Name der neuen Sammlung', create:'Erstellen', collectionEntries:'Einträge', readingLists:'Leselisten', collections:'Sammlungen', newCollection:'Neue Sammlung', collectionName:'Sammlungsname', save:'Speichern', cancel:'Abbrechen', collection:'Sammlung', deleteCollectionQuestion:'Diese Sammlung löschen?', delete:'Löschen', rename:'Umbenennen', noCollections:'Noch keine Sammlungen. Erstelle links eine neue.', emptyCollection:'Diese Sammlung hat noch keine Einträge.', entryUnavailable:'Eintrag nicht verfügbar', remove:'entfernen', saveOrShare:'speichern oder teilen', saveThisEntry:'Diesen Eintrag speichern', saveIntro:'Wähle einen visuellen Stil für den Eintrag. Die Wörter bleiben gleich, die Darstellung ändert sich.', savedEntry:'GESPEICHERTER EINTRAG', definitionLower:'Definition', inUse:'im Einsatz', pickPersonality:'Stil auswählen', downloadPng:'PNG herunterladen', copyText:'Text kopieren', copyLink:'Link kopieren', share:'Teilen', tutorialLabel:'The AI Almanac Tutorial', tutorialHowTo:'So verwendest du The AI Almanac', step:'Schritt', of:'von', closeTutorial:'Tutorial schließen', back:'Zurück', finish:'Fertig', next:'Weiter', skipTutorial:'Tutorial überspringen' },
  hi: { ...en, close:'बंद करें', open:'खोलें', bookmarks:'बुकमार्क', readingHistory:'पढ़ने का इतिहास', savedEntries:'सहेजी गई प्रविष्टियाँ', recentlyOpened:'हाल में खोली गई', noBookmarks:'अभी कोई बुकमार्क नहीं है।', noHistory:'अभी कोई पढ़ने का इतिहास नहीं है।', completeIndex:'पूरा इंडेक्स', everyFiledTerm:'सभी दर्ज शब्द', entries:'प्रविष्टियाँ', indexSections:'इंडेक्स खंड', updatedFieldEdition:'अपडेटेड फील्ड संस्करण', filterIndex:'पूरा इंडेक्स फ़िल्टर करें', filterTerms:'शब्द, aliases या categories फ़िल्टर करें…', filterCategory:'category के अनुसार फ़िल्टर करें', allCategories:'सभी categories', jumpToLetter:'इंडेक्स अक्षर पर जाएँ', noEntriesUnder:'इसके अंतर्गत कोई प्रविष्टि नहीं', noTermsMatch:'कोई शब्द मेल नहीं खाता', clearFilter:'फ़िल्टर साफ़ करें', timelineEyebrow:'समयरेखा', timelineTitle:'शब्द कैसे विकसित हुए', openThisTerm:'यह शब्द खोलें', compareEyebrow:'साथ-साथ पढ़ें', compareTitle:'शब्दों की तुलना करें', compareIntro:'दोनों definitions साथ पढ़ें और पूरी note देखने के लिए किसी प्रविष्टि को खोलें।', definition:'परिभाषा', inPractice:'व्यवहार में', addThisEntry:'यह प्रविष्टि जोड़ें', addToCollection:'संग्रह में जोड़ें', collectionPickerClose:'संग्रह चयन बंद करें', newCollectionName:'नए संग्रह का नाम', create:'बनाएँ', collectionEntries:'प्रविष्टियाँ', readingLists:'पढ़ने की सूचियाँ', collections:'संग्रह', newCollection:'नया संग्रह', collectionName:'संग्रह का नाम', save:'सहेजें', cancel:'रद्द करें', collection:'संग्रह', deleteCollectionQuestion:'यह संग्रह हटाएँ?', delete:'हटाएँ', rename:'नाम बदलें', noCollections:'अभी कोई संग्रह नहीं है। बाईं ओर से नया संग्रह बनाएँ।', emptyCollection:'इस संग्रह में अभी कोई प्रविष्टि नहीं है।', entryUnavailable:'प्रविष्टि उपलब्ध नहीं', remove:'हटाएँ', saveOrShare:'सहेजें या साझा करें', saveThisEntry:'यह प्रविष्टि सहेजें', saveIntro:'प्रविष्टि के लिए visual style चुनें। शब्द वही रहेंगे, प्रस्तुति बदलेगी।', savedEntry:'सहेजी गई प्रविष्टि', definitionLower:'परिभाषा', inUse:'उपयोग में', pickPersonality:'स्टाइल चुनें', downloadPng:'PNG डाउनलोड करें', copyText:'टेक्स्ट कॉपी करें', copyLink:'लिंक कॉपी करें', share:'साझा करें', tutorialLabel:'The AI Almanac ट्यूटोरियल', tutorialHowTo:'The AI Almanac का उपयोग कैसे करें', step:'चरण', of:'में से', closeTutorial:'ट्यूटोरियल बंद करें', back:'पीछे', finish:'समाप्त करें', next:'अगला', skipTutorial:'ट्यूटोरियल छोड़ें' }
};

export function getOverlayStrings(locale: SupportedLocale = getRuntimeLocale()): OverlayStrings {
  return locale === 'en' ? en : overlays[locale];
}
