#!/usr/bin/env python3
"""Generate static Bengali definitions for every AI Almanac term.

The output is committed to src/i18n/bengaliDefinitions.generated.ts so the
Bengali edition remains static, crawlable, and independent of runtime
translation services. Curated Bengali copy in src/i18n/bengali.ts still wins
at runtime for entries that have hand-written mode-specific content.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import torch
from transformers import MarianMTModel, MarianTokenizer

ROOT = Path(__file__).resolve().parents[1]
TERMS_PATH = ROOT / "src" / "data" / "terms.ts"
OUTPUT_PATH = ROOT / "src" / "i18n" / "bengaliDefinitions.generated.ts"
MODEL_ID = "Helsinki-NLP/opus-mt-en-inc"
EXPECTED_TERM_COUNT = 791
BATCH_SIZE = 16

TERM_PATTERN = re.compile(
    r'\{\s*"word"\s*:\s*("(?:\\.|[^"\\])*")'
    r'.*?"definition"\s*:\s*("(?:\\.|[^"\\])*")',
    re.DOTALL,
)
BENGALI_PATTERN = re.compile(r"[\u0980-\u09FF]")


def load_terms() -> list[tuple[str, str]]:
    source = TERMS_PATH.read_text(encoding="utf-8")
    start = source.find("export const terms: Term[] = [")
    if start < 0:
        raise RuntimeError("Could not find the terms array in src/data/terms.ts")

    # Do not accidentally consume later helper objects that also contain
    # definition-like strings.
    end_markers = [
        source.find("export const sortedTerms", start),
        source.find("export const termsByWord", start),
        source.find("const sortedTerms", start),
    ]
    valid_ends = [position for position in end_markers if position >= 0]
    end = min(valid_ends) if valid_ends else len(source)
    term_source = source[start:end]

    pairs: list[tuple[str, str]] = []
    for match in TERM_PATTERN.finditer(term_source):
        word = json.loads(match.group(1))
        definition = json.loads(match.group(2))
        pairs.append((word, definition))

    if len(pairs) != EXPECTED_TERM_COUNT:
        raise RuntimeError(
            f"Expected {EXPECTED_TERM_COUNT} terms, parsed {len(pairs)}. "
            "Refusing to generate a partial Bengali corpus."
        )
    return pairs


def translate_definitions(definitions: list[str]) -> list[str]:
    tokenizer = MarianTokenizer.from_pretrained(MODEL_ID)
    model = MarianMTModel.from_pretrained(MODEL_ID)
    model.eval()

    translated: list[str] = []
    for offset in range(0, len(definitions), BATCH_SIZE):
        batch = definitions[offset : offset + BATCH_SIZE]
        # opus-mt-en-inc requires a sentence-initial target language token.
        tagged = [f">>ben<< {text}" for text in batch]
        encoded = tokenizer(
            tagged,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=512,
        )
        with torch.inference_mode():
            generated = model.generate(
                **encoded,
                num_beams=4,
                max_new_tokens=256,
                renormalize_logits=True,
            )
        translated.extend(
            " ".join(text.split())
            for text in tokenizer.batch_decode(generated, skip_special_tokens=True)
        )
        print(f"Translated {min(offset + BATCH_SIZE, len(definitions))}/{len(definitions)}")

    return translated


def validate(pairs: list[tuple[str, str]], translations: list[str]) -> None:
    if len(translations) != EXPECTED_TERM_COUNT:
        raise RuntimeError(
            f"Expected {EXPECTED_TERM_COUNT} translations, got {len(translations)}"
        )

    failures: list[str] = []
    for (word, english), bengali in zip(pairs, translations, strict=True):
        if not bengali.strip():
            failures.append(f"{word}: empty translation")
            continue
        if bengali.strip() == english.strip():
            failures.append(f"{word}: translation is unchanged English")
            continue
        if not BENGALI_PATTERN.search(bengali):
            failures.append(f"{word}: no Bengali characters")

    if failures:
        preview = "\n".join(failures[:20])
        raise RuntimeError(
            f"Bengali translation validation failed for {len(failures)} entries:\n{preview}"
        )


def write_typescript(pairs: list[tuple[str, str]], translations: list[str]) -> None:
    lines = [
        "// This file is generated by scripts/generate-bengali-definitions.py.",
        "// Do not edit generated translations here; hand-curated overrides belong in bengali.ts.",
        "",
        "export const bengaliDefinitions: Record<string, string> = {",
    ]

    for (word, _), translation in zip(pairs, translations, strict=True):
        key = json.dumps(word.strip().lower(), ensure_ascii=False)
        value = json.dumps(translation, ensure_ascii=False)
        lines.append(f"  {key}: {value},")

    lines.extend(
        [
            "};",
            "",
            "export function getBengaliDefinition(termKey: string): string | null {",
            "  return bengaliDefinitions[termKey.trim().toLowerCase()] || null;",
            "}",
            "",
        ]
    )
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    pairs = load_terms()
    translations = translate_definitions([definition for _, definition in pairs])
    validate(pairs, translations)
    write_typescript(pairs, translations)
    print(f"Wrote {EXPECTED_TERM_COUNT} Bengali definitions to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
